language: ruby
rbenv:
- 2.4.1
services:
- postgresql
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: aMT3PCgv/DoLHC9EodcO9qsnh1Recyw59oiH4SSeh2x6D4JQqX+jjL6YuB4yh9Ax9rQCR3kvV4N9JjsvRKW/CQ6BlSVDcMaHviYjaX0lITBY0JixB3TU+IX71zs2J24lwnktorc9m9A/HpWog2PiESkeHTTIpYn1j/USGsVauhRQY95UQ8Oaws05mxuFoC7eGbmD4zT73MH+vYKC7I0yvFHQ2pc4gIkv6AbjIHyaFXCnntZQXR1T7YDYoPBKjBi4KB7o2WrzjkN8g9YJQ+2gg8jP/MqliePvnPvm/BGid/hDTvKi60xFksqNzqXPsK1jOIqGMBoqftJmkAcd8Fyi1VqN+XA/SkaQMiRtMxSK8PzJN9kn7R1eWfalZ89/Pg/XPf32BslaPuTJdL+JcmvtweihhixFyDsd2WWOHwvpUdvo1KEKer4rJnmp/amKEJzT/H/B76o8tbYKL+AbotNjSTV7sZQvk+7V4OqImqVkcKxRiswQS1PjGayF8juyBacMlVWmXseIIptlEUOfJ307ADmBwiWsuJNMPsaBdjOHYq01BVBvIPismG9tEPFWM8Q8tZ4GZpnbeHue/ZBvHacup9rNjbBKTQvk2fNxTV3Pgw8nbZROFqXysByfpK8HXAGH1+PItu443b2AKAOUqg184iHZP+gL1dqobNxs4R1bnj0=
  app: sweater-weather-mr
  on:
    repo: mronauli/sweater_weather
env:
  global:
    secure: jFql8O08WMIhB7rtyIXuI8Z2LQ8b5r6em4RUVSITVEUTxBH8Cl7QBK/6ynzd/koxIXpXI/vTQANk1O/xJa5EqqXeYof+o392xmECP3/giLesp7sXFLg9SCbDmKNWljqGK5hdhPMJ+Rzc/+8UeqpWRycdzM7U5mwS/jepGa+EiNlXtI9ENi7L1zv2giv6tIGO4CL/HL2xghgPqp5CahDGwaGUoT9QyjcfrZcWMMnAnKvZyd/HW4rY2Mt+28R0ktKmCVOvAhZ6aW9Ur5YVP1CG7qSOCvg79ZM1cFWaIiE3F9YNaxCGd7w9zqHURfOc77Y7h2kn8CdVL5t6QQlWEFrqt0gVqzSmAB49HhRPD3YYLYOABK5aiTz9qVgsiJ6DZC1+I9/ncvxrXLynFl3NIOmkK7nyNyn+OGVrhPzZGqVWkffkBACDqbteSFrYM8WWnLofkro72TzB3F34rI/87uWe9mhgdjnHeN1NFsYpJRXeJghbCnlVnHuEb/QVPRaWM00OmIZWFg+orEoOzvgRs+uqLgi1zefKlqYsv7/033Uqp2CZrKXN497+Obqjc9EsN80r3X0TO+CnKzTQisR94+aYALlZzy1qd8VT+gkgGGiYS0Y8xGPfFykzuX1q97Lqmfy8ShgagiUxIjSQrx5pKkwWpL9u4lwJvph+la7JXZlM3/A=
