language: ruby
rbenv:
  - 2.4.1
services:
  - postgresql
script:
  - bundle exec rails db:{create,migrate} RAILS_ENV=test
  - bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: "aMT3PCgv/DoLHC9EodcO9qsnh1Recyw59oiH4SSeh2x6D4JQqX+jjL6YuB4yh9Ax9rQCR3kvV4N9JjsvRKW/CQ6BlSVDcMaHviYjaX0lITBY0JixB3TU+IX71zs2J24lwnkt
orc9m9A/HpWog2PiESkeHTTIpYn1j/USGsVauhRQY95UQ8Oaws05mxuFoC7eGbmD4zT73MH+vYKC7I0yvFHQ2pc4gIkv6AbjIHyaFXCnntZQXR1T7YDYoPBKjBi4KB7o2WrzjkN8g9YJQ+2
gg8jP/MqliePvnPvm/BGid/hDTvKi60xFksqNzqXPsK1jOIqGMBoqftJmkAcd8Fyi1VqN+XA/SkaQMiRtMxSK8PzJN9kn7R1eWfalZ89/Pg/XPf32BslaPuTJdL+JcmvtweihhixFyDsd2W
WOHwvpUdvo1KEKer4rJnmp/amKEJzT/H/B76o8tbYKL+AbotNjSTV7sZQvk+7V4OqImqVkcKxRiswQS1PjGayF8juyBacMlVWmXseIIptlEUOfJ307ADmBwiWsuJNMPsaBdjOHYq01BVBvI
PismG9tEPFWM8Q8tZ4GZpnbeHue/ZBvHacup9rNjbBKTQvk2fNxTV3Pgw8nbZROFqXysByfpK8HXAGH1+PItu443b2AKAOUqg184iHZP+gL1dqobNxs4R1bnj0="
  app: sweater-weather-mr
  on:
    repo: mronauli/sweater_weather
