language: ruby
rbenv:
- 2.4.1
services:
- postgresql
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: CjhOgUA8c09vY8JO/oWgaWdvZnj/2UOpn22mBPy8lKb4mzxzB+rauobcrcXdZaYKRk9wEn6lAG5uX9HPimRg9j3NAAo36qNA09MVaMShpiqCUNKo52SyST8K4vjlNI6d2SBqIT5AeZsaaPbhZ7jUNRlgr5bVWM08Uv+8F7TIsdqrZmZpVIfEliBQn9+imIqAQ8Z6Fp28c22NO56qd5QcrXyefIMKqMBgS8GkFyvotBY0fscx3PV+Te6A6T6fCal3u+XMzmBSph+cLfqNYs9A2rVXO4YJQNgZSgeAB0vfYyZ+qNzt35dTc3VRrbHhPCy8fF9fTPZazPdQZnXzbOxIU6UxjCZVzhVRwZlxcx7GZnq9KJHcx1jB/haPlYJY8rgB2o9FseNrrCJ9cFLqx9gKPPJ/a8v0yHwAd+3gsGZJFTrzD0O79kTSEAeE+3tbPff6t7GNPbePny3+5mBwdRr8Ie3gsrWCL1uoab9EIZ3pQ6/TLyOfKEf66ibH28MSYMTnTK0ONZ291SsFb4yrcuTElsGwpK1UcAJs1zv+YQ4PdHx3LI05oIShcGMNmORjxIi5twchD0tIwk0wHGzlePYFBTiTqtoZILu+8AuVxqSi++YbxI0NP9VYXDJ9Ff2JxBcG8rNk1XzMGNLYtl1jXc8Ijx+P+k6e1cYz6n6HQSjUV1U=
  app: sweater-weather-mr
  skip_cleanup: true
  on:
    repo: mronauli/sweater_weather
env:
  global:
    secure: jFql8O08WMIhB7rtyIXuI8Z2LQ8b5r6em4RUVSITVEUTxBH8Cl7QBK/6ynzd/koxIXpXI/vTQANk1O/xJa5EqqXeYof+o392xmECP3/giLesp7sXFLg9SCbDmKNWljqGK5hdhPMJ+Rzc/+8UeqpWRycdzM7U5mwS/jepGa+EiNlXtI9ENi7L1zv2giv6tIGO4CL/HL2xghgPqp5CahDGwaGUoT9QyjcfrZcWMMnAnKvZyd/HW4rY2Mt+28R0ktKmCVOvAhZ6aW9Ur5YVP1CG7qSOCvg79ZM1cFWaIiE3F9YNaxCGd7w9zqHURfOc77Y7h2kn8CdVL5t6QQlWEFrqt0gVqzSmAB49HhRPD3YYLYOABK5aiTz9qVgsiJ6DZC1+I9/ncvxrXLynFl3NIOmkK7nyNyn+OGVrhPzZGqVWkffkBACDqbteSFrYM8WWnLofkro72TzB3F34rI/87uWe9mhgdjnHeN1NFsYpJRXeJghbCnlVnHuEb/QVPRaWM00OmIZWFg+orEoOzvgRs+uqLgi1zefKlqYsv7/033Uqp2CZrKXN497+Obqjc9EsN80r3X0TO+CnKzTQisR94+aYALlZzy1qd8VT+gkgGGiYS0Y8xGPfFykzuX1q97Lqmfy8ShgagiUxIjSQrx5pKkwWpL9u4lwJvph+la7JXZlM3/A=
